#!/usr/bin/env python3
"""Build the Confluence edition of the storage pricing tool.

Outputs (in dist/confluence/):
  ocvs-storage-tool.js   - the whole tool in one file (page, styles, PptxGenJS,
                           price data, app and slide builder). Attach it to the
                           Confluence page. Nothing is loaded from the internet.
  confluence-macro.html  - the small loader to paste into the page's HTML macro.
  preview.html           - local preview that mimics Confluence.

The loader shows the tool in an iframe, so Confluence's CSS and scripts cannot
interfere with it (and it cannot interfere with the page).

Run from the repo root:  python3 tools/build_confluence.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "confluence"
OUT.mkdir(parents=True, exist_ok=True)
read = lambda p: (ROOT / p).read_text(encoding="utf-8")
script = lambda js: "<script>" + js.replace("</script", "<\\/script") + "</script>"

html = read("index.html")
html = html.replace("<head>", '<head>\n<base target="_blank">', 1)   # links open in a new tab, not inside the frame
html = re.sub(r'<header class="top">.*?</header>\s*', "", html, flags=re.S)   # the Confluence page has its own title
html = re.sub(r'<link rel="stylesheet" href="css/style.css[^"]*">',
              lambda m: "<style>" + read("css/style.css") + "\nbody{background:#fff}</style>", html)
html = re.sub(r'<script src="https://cdn.jsdelivr.net/npm/pptxgenjs[^"]*"></script>',
              lambda m: script(read("vendor/pptxgen.bundle.js")), html)
for f in ["data/storage.js", "data/regions.js", "js/ppt.js", "js/app.js"]:
    html = re.sub(r'<script src="' + re.escape(f) + r'[^"]*"></script>', lambda m, f=f: script(read(f)), html)
assert "<script src=" not in html and "<link rel=\"stylesheet\"" not in html, "an external file is still referenced"

(OUT / "ocvs-storage-tool.js").write_text(
    "/* OCVS External Storage Pricing - Confluence edition. Generated by tools/build_confluence.py; do not edit. */\n"
    "window.OCVS_STORAGE_HTML = " + json.dumps(html) + ";\n", encoding="utf-8")

LOADER = """<div id="ocvs-storage"><div style="padding:24px;font-family:Arial,sans-serif;color:#6b778c">Loading the OCVS storage pricing tool…</div></div>
<script>
(function () {
  // Loads ocvs-storage-tool.js attached to this page and shows the tool in a self-sizing iframe.
  var box = document.getElementById("ocvs-storage");
  var meta = function (n) { var m = document.querySelector('meta[name="' + n + '"]'); return m ? m.content : ""; };
  var ctx = meta("ajs-context-path"), pageId = meta("ajs-page-id") || (window.AJS && AJS.params && AJS.params.pageId);
  var url = ctx + "/download/attachments/" + pageId + "/ocvs-storage-tool.js?api=v2&t=" + Math.floor(Date.now() / 600000);
  fetch(url, { credentials: "same-origin" })
    .then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.text(); })
    .then(function (code) {
      var w = {}; new Function("window", code)(w);
      var f = document.createElement("iframe");
      f.title = "OCVS external storage pricing";
      f.style.cssText = "width:100%;border:0;display:block;min-height:600px";
      f.srcdoc = w.OCVS_STORAGE_HTML;
      f.onload = function () {
        var d = f.contentDocument, fit = function () { f.style.height = d.documentElement.scrollHeight + "px"; };
        fit(); new ResizeObserver(fit).observe(d.body);
      };
      box.innerHTML = ""; box.appendChild(f);
    })
    .catch(function (e) {
      box.innerHTML = '<div style="padding:20px;border:1px solid #f5c2c0;background:#fdecea;border-radius:10px;font-family:Arial,sans-serif;color:#8a1c14">' +
        'Could not load the storage pricing tool (' + e.message + '). Check that <b>ocvs-storage-tool.js</b> is attached to this page.</div>';
    });
})();
</script>
"""
(OUT / "confluence-macro.html").write_text(LOADER, encoding="utf-8")

PREVIEW = """<!doctype html><html><head><meta charset="utf-8"><title>Confluence preview</title>
<meta name="ajs-context-path" content=""><meta name="ajs-page-id" content="PREVIEW">
<style>body{margin:0;background:#fff;font-family:Arial,sans-serif}.cf-top{background:#403a37;color:#fff;padding:14px 24px;font-size:20px}
.cf-page{max-width:1300px;margin:0 auto;padding:24px 40px}.cf-page h1.title{font-size:30px;color:#172b4d;font-weight:500;margin:0 0 20px}</style>
<script>window.define=function(){};window.define.amd={};/* mimic Confluence's AMD loader */</script>
</head><body><div class="cf-top">Central Confluence (preview)</div><div class="cf-page"><h1 class="title">OCVS External Storage Pricing</h1>
""" + LOADER.replace('ctx + "/download/attachments/" + pageId + "/ocvs-storage-tool.js?api=v2&t="', '"ocvs-storage-tool.js?t="') + "</div></body></html>"
(OUT / "preview.html").write_text(PREVIEW, encoding="utf-8")

print("built", OUT, round((OUT / "ocvs-storage-tool.js").stat().st_size / 1024), "KB")
